# Generated by Django 5.0.2 on 2024-04-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
