# Generated by Django 5.0.2 on 2024-04-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
