# Generated by Django 5.0.2 on 2024-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
    ]
