# Generated by Django 5.0.2 on 2024-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='reviews',
            field=models.JSONField(default=dict),
        ),
    ]
