# Generated by Django 5.0.2 on 2024-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_alter_link_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(default='Отзыв', max_length=1000),
        ),
    ]
