# Generated by Django 4.2.11 on 2024-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=5),
        ),
    ]
