# Generated by Django 5.0.2 on 2024-04-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='reviews',
        ),
    ]
