# Generated by Django 5.0.2 on 2024-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_remove_link_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='stars',
            field=models.IntegerField(default=5),
        ),
    ]
